-- LLM 生成参数
-- 2026-07-06

ALTER TABLE llm_providers 
  ADD COLUMN IF NOT EXISTS temperature REAL DEFAULT 0.7,
  ADD COLUMN IF NOT EXISTS top_p REAL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS max_tokens INTEGER DEFAULT 2048,
  ADD COLUMN IF NOT EXISTS presence_penalty REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS frequency_penalty REAL DEFAULT 0;
